---
title: "xy_morph_by_cluster_scratch"
author: "Metka"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Desktop/OneDrive - Queen Mary, University of London/experiments/Project2/2024.03.09_DAPT12/Scratch/t16")
```

```{r}
library(readxl)
library(tibble)
library(tidyr)
library(dplyr)
library(ggplot2)
library(stringr)
library(ggplate)
library(reshape2)
library(janitor)
library(ggplot2)
library(data.table)
library(reshape2)
library(gplots)
```




```{r}
setwd("~/Library/CloudStorage/OneDrive-QueenMary,UniversityofLondon/experiments/Project2/2024.04.19_DBT6/Scratch/t16/Morph")
# Specify the file name
excel_file <- "Metka_SAMP_sub11_04_2024.2024.04.26.20.46.02.xls"

# Function to read sheets containing a specific substring
read_sheets_containing <- function(file, substr) {
  all_sheets <- excel_sheets(file)
  selected_sheets <- grep(substr, all_sheets, value = TRUE)
  dfs_list <- lapply(selected_sheets, function(sheet) read_excel(file, sheet = sheet, skip = 1))
  return(do.call(rbind, dfs_list))
}

# Read sheets containing 'NC1' into combined dataframe
NC <- read_sheets_containing(excel_file, "NC1")

# Read sheets containing 'NC_Sc2' into combined dataframe
sc2 <- read_sheets_containing(excel_file, "NC_Sc2")

# Read sheets containing 'NC_Sc1' into combined dataframe
sc1 <- read_sheets_containing(excel_file, "NC_Sc1")

NC$position <- as.character(paste(NC$X_N_NC, NC$Y_N_NC))
sc1$position <- as.character(paste(sc1$X_Sc1__, sc1$Y_NC_Sc1__))
sc2$position <- as.character(paste(sc2$X_NC_Sc2__, sc2$Y_NC_Sc2__))



NC$area <- ifelse(NC$position %in% sc1$position, "Zone 1 t16",  
                  ifelse(NC$position %in% sc2$position, "Zone 2 t16", "Zone 3 t16"))


list(unique(NC$area))
table(NC$area)

NC <- NC%>% 
  separate(Section, into=c("row", "Column"), sep = ' - ')
# Separate Section into row and column

NC$well <- paste(NC$row, NC$Column) # Create well identifier by combining row and column
```

```{r}
NC_c7 <- NC %>% 
  filter(well == 'C 7') # Filter data for well 'C 7' 


NC_c7 <- NC_c7[-c(28, 60)] # Remove NA columns by index
allcompounds.cl.c7 <- NC_c7[-c(1:3, 13:14, 8:9, 19:20, 30, 35:36, 42:43, 48:49, 55:56, 62:68)] # Remove non-numeric and spatial columns

allcompounds.cl.scaled.c7 <- scale(allcompounds.cl.c7) # Scale numeric data

allcompounds.cl.scaled.df.c7 <- as.data.frame(allcompounds.cl.scaled.c7) # Convert to data frame
```
```{r}
library(umap) # Load UMAP library

umap <- umap(allcompounds.cl.scaled.df.c7, na.rm = TRUE) # Perform UMAP

df <- data.frame(umap$layout) # Convert UMAP layout to data frame
```
```{r}
library(factoextra)   #check for optimal number of clusters
fviz_nbclust(df, kmeans, method = "wss") +
      labs(subtitle = "Elbow method")

```

```{r}
# Run Louvain clustering with the optimal resolution parameter
graph <- bluster::makeSNNGraph(df[1:2])
clust <- igraph::cluster_louvain(graph, weights = NULL, resolution = 0.02)
df$clust <- factor(clust$membership)

umap.plot <- ggplot(df, aes(X1, X2)) +
  geom_point(size=0.4)
umap.plot

# Create the scatter plot with points colored by their cluster assignment
cluster_plot <- ggplot(df, aes(X1, X2, colour = clust)) +
  geom_point() 


# Print the plot
print(cluster_plot)
```

```{r}
# Add all measures if you want to investigate how they behave on the UMAP
df1 <- cbind(df, NC_c7) # Combine UMAP layout with original data

# Create scatter plot with points colored by cluster assignment
cluster_plot <- ggplot(df1, aes(X_N_NC, Y_N_NC, colour = clust)) +
  geom_point(size = 1) +
  labs(title = "Scatter Plot Colored by Cluster", x = "X", y = "Y", colour = "Cluster") +
  theme_minimal()

# Print the plot
print(cluster_plot)
```

```{r}
NC_c7_zone1 <- NC_c7 %>% 
  filter(area == 'Zone 1 t16') # Filter data by area you're interested in' 

allcompounds.cl.c7.zone1 <- NC_c7_zone1[-c(1:3, 13:14, 8:9, 19:20, 30, 35:36, 42:43, 48:49, 55:56, 62:68)] # Remove non-numeric and spatial columns

allcompounds.cl.scaled.c7.zone1 <- scale(allcompounds.cl.c7.zone1) # Scale numeric data

allcompounds.cl.scaled.df.c7.zone1 <- as.data.frame(allcompounds.cl.scaled.c7.zone1) # Convert to data frame
```
```{r}
library(umap) # Load UMAP library

umap <- umap(allcompounds.cl.scaled.df.c7.zone1, na.rm = TRUE) # Perform UMAP

df <- data.frame(umap$layout) # Convert UMAP layout to data frame
```
```{r}
library(factoextra)   #check for optimal number of clusters
fviz_nbclust(df, kmeans, method = "wss") +
      labs(subtitle = "Elbow method")

```

```{r}
# Run Louvain clustering with the optimal resolution parameter
graph <- bluster::makeSNNGraph(df[1:2])
clust <- igraph::cluster_louvain(graph, weights = NULL, resolution = 0.1)
df$clust <- factor(clust$membership)

umap.plot <- ggplot(df, aes(X1, X2)) +
  geom_point(size=0.4)
umap.plot

# Create the scatter plot with points colored by their cluster assignment
cluster_plot <- ggplot(df, aes(X1, X2, colour = clust)) +
  geom_point() 


# Print the plot
print(cluster_plot)
```

```{r}
# Add all measures if you want to investigate how they behave on the UMAP
df1 <- cbind(df, NC_c7_zone1) # Combine UMAP layout with original data

# Create scatter plot with points colored by cluster assignment
cluster_plot <- ggplot(df1, aes(X_N_NC, Y_N_NC, colour = clust)) +
  geom_point(size = 1) +
  labs(title = "Scatter Plot Colored by Cluster", x = "X", y = "Y", colour = "Cluster") +
  theme_minimal()

# Print the plot
print(cluster_plot)
```















